[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "remote-debug"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.4.2,<9"
black = ">=25.1.0,<26"
pre-commit = ">=4.3.0,<5"
pytest-mock = ">=3.15.1,<4"
requests = ">=2.32.5,<3"
conda-build = ">=25.9.0,<26"

[pypi-dependencies]
remote_debug = { path = ".", editable = true }
