name: Publish to Anaconda

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.1.0, v1.2.3 etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    # No matrix is needed for a noarch build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          # We can use any recent python for the build environment
          python-version: "3.12"

      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client

      - name: Build Conda package
        shell: bash -l {0}
        run: |
          # No --python flag needed, conda-build will use the noarch setting from meta.yaml
          conda build ./conda.recipe --output-folder ./build_output

      - name: Upload package to Anaconda
        shell: bash -l {0}
        run: |
          # Point to the correct 'noarch' directory
          anaconda -t ${{ secrets.ANACONDE_TOKEN }} upload ./build_output/noarch/remote-debug-*.conda