name: Publish to Anaconda

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.1.0, v1.2.3 etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    # Define a build matrix for different Python versions
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          # Use the Python version from the matrix
          python-version: ${{ matrix.python-version }}

      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client

      - name: Build Conda package
        shell: bash -l {0}
        run: |
          # The --python flag tells conda-build which version to build for
          conda build ./conda.recipe --python ${{ matrix.python-version }} --output-folder ./build_output

      - name: Upload package to Anaconda
        shell: bash -l {0}
        run: |
          # The package is no longer in 'noarch', but in a platform-specific folder
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload ./build_output/linux-64/remote-debug-*.conda